spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&user=postgres.rgycsurqbyesaeehqvdz&password=${DB_PASSWORD}&prepareThreshold=0
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: sR6tiDCqgmUWHNmpRKQrqvZZ6YfLQVSaysud9sNLG6U=
  expiration: 86400000